### ISSUE TITLE
Typo in get_magnetic_transition_operator function

### ISSUE THREAD

**Issue by ws-general** [qt3uw/qt3qutipsandbox#13]
The first tensor product should use identity(twonplus1(p.nuclear_spin)), not identity(twonplus1(p.electron_spin)).

![typo](https://user-images.githubusercontent.com/61124096/228113624-01b208ea-5047-4591-b588-2585733f5747.png)

**Comment by mfparsons314** [comment]
Resolved with commit 02765a1
